import {ClerkProvider} from "@clerk/nextjs";
import type {Metadata} from "next";
import {Inter} from "next/font/google";
import "./globals.css";

import QueryProvider from "@/components/provider/query-provider";
import {Toaster} from "sonner";

// const inter = Inter({subsets: ["latin"]});
const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
  title: {
    default: "Weather App",
    template: "%s | Weather App",
  },
  description: "Generated by create next app",
};

export default function RootLayout({children}: {children: React.ReactNode}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className}>
          <QueryProvider>
            <Toaster />
            {children}
          </QueryProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
